name: Rename Template Repository
on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  rename:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Apply Rename
        uses: kota65535/github-template-rename-action@v1
        with:
          from-name: project-name
          pr-title: "Rename from Template"
          commit-message: "Replaced instances of project-name with repository name"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          paths-ignore: |
            .github/**

      - name: Delete Workflow File
        run: |
          git rm -f .github/workflows/rename.yml
          git commit -m "Delete rename.yml" || echo "Nothing to commit"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}
          git push origin template-rename
